/**
 * Customer Create Form Component
 * 
 * Form for creating a new customer with role-based customer type restrictions
 * All custom code is proprietary and not open source.
 */

import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { CreateCustomerDto, customersService } from '../customers.service';
import { Product } from '../../products/products.service';
import { ProductMultiSelect } from '../../products/components/ProductMultiSelect';
import { Input } from '../../components/ui/Input';
import { Button } from '../../components/ui/Button';
import { useAuth } from '../../auth/AuthContext';
import { isFrontendSpecialist, isBackendSpecialist, isDirector, isAdmin } from '../../common/constants/roles';
import { toast } from 'react-toastify';
import {
  CUSTOMER_CREATE_SUCCESS,
  CUSTOMER_CREATE_WITH_ASSOCIATIONS_SUCCESS,
  CUSTOMER_CREATE_ASSOCIATIONS_PARTIAL_FAILURE,
  CUSTOMER_CREATE_ASSOCIATIONS_ALL_FAILURE,
  MANAGE_ASSOCIATIONS_IN_DETAIL,
} from '../../common/constants/error-messages';
import { AssociationType } from '../../products/types/association-types';

interface CustomerCreateFormProps {
  onSubmit: (data: CreateCustomerDto) => Promise<void>;
  onCancel: () => void;
}

export const CustomerCreateForm: React.FC<CustomerCreateFormProps> = ({
  onSubmit,
  onCancel,
}) => {
  const { user } = useAuth();
  const [formData, setFormData] = useState<CreateCustomerDto>({
    name: '',
    customerType: isFrontendSpecialist(user?.role) ? 'BUYER' : isBackendSpecialist(user?.role) ? 'SUPPLIER' : 'BUYER',
    domainName: '',
    address: '',
    city: '',
    state: '',
    country: '',
    postalCode: '',
    industry: '',
    employees: undefined,
    website: '',
    phone: '',
    email: '',
    notes: '',
  });

  const navigate = useNavigate();
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Association state
  const [isAssociationExpanded, setIsAssociationExpanded] = useState(false);
  const [selectedProducts, setSelectedProducts] = useState<Product[]>([]);

  // Get available customer types based on user role
  const getAvailableCustomerTypes = (): ('BUYER' | 'SUPPLIER')[] => {
    if (isFrontendSpecialist(user?.role)) {
      return ['BUYER'];
    }
    if (isBackendSpecialist(user?.role)) {
      return ['SUPPLIER'];
    }
    if (isDirector(user?.role) || isAdmin(user?.role)) {
      return ['BUYER', 'SUPPLIER'];
    }
    return ['BUYER', 'SUPPLIER']; // Default
  };

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};

    const trimmedName = formData.name?.trim() || '';
    if (trimmedName.length === 0) {
      newErrors.name = '客户名称不能为空';
    } else if (trimmedName.length > 255) {
      newErrors.name = '客户名称长度不能超过255个字符';
    }

    // Customer code is now auto-generated by backend, no validation needed

    if (!formData.customerType) {
      newErrors.customerType = '客户类型不能为空';
    }

    if (formData.address && formData.address.length > 1000) {
      newErrors.address = '地址长度不能超过1000个字符';
    }

    if (formData.industry && formData.industry.length > 100) {
      newErrors.industry = '行业长度不能超过100个字符';
    }

    if (formData.employees !== undefined) {
      if (formData.employees < 1 || formData.employees > 1000000) {
        newErrors.employees = '员工数必须在1-1000000之间';
      }
    }

    if (formData.notes && formData.notes.length > 5000) {
      newErrors.notes = '备注长度不能超过5000个字符';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validate()) {
      return;
    }

    setIsSubmitting(true);
    try {
      const submitData: CreateCustomerDto = {
        ...formData,
        // Remove empty strings and convert to undefined
        domainName: formData.domainName?.trim() || undefined,
        address: formData.address?.trim() || undefined,
        city: formData.city?.trim() || undefined,
        state: formData.state?.trim() || undefined,
        country: formData.country?.trim() || undefined,
        postalCode: formData.postalCode?.trim() || undefined,
        industry: formData.industry?.trim() || undefined,
        website: formData.website?.trim() || undefined,
        phone: formData.phone?.trim() || undefined,
        email: formData.email?.trim() || undefined,
        notes: formData.notes?.trim() || undefined,
        // Remove customerCode - backend will auto-generate
        customerCode: undefined,
      };

      // First, create the customer
      const createdCustomer = await customersService.createCustomer(submitData);

      // Then, create associations if products are selected
      if (selectedProducts.length > 0) {
        const associationPromises = selectedProducts.map(async (product) => {
          // Determine association type based on customer type
          const associationType: AssociationType =
            formData.customerType === 'BUYER'
              ? 'POTENTIAL_BUYER'
              : 'POTENTIAL_SUPPLIER';

          try {
            await customersService.createCustomerProductAssociation(
              createdCustomer.id,
              product.id,
              associationType,
            );
            return { success: true, product };
          } catch (error: unknown) {
            const errorMessage = error instanceof Error ? error.message : '未知错误';
            return { success: false, product, error: errorMessage };
          }
        });

        // Use Promise.allSettled to allow partial failures
        const results = await Promise.allSettled(associationPromises);
        const successful = results
          .filter((r) => r.status === 'fulfilled' && r.value.success)
          .map((r) => (r.status === 'fulfilled' ? r.value.product : null))
          .filter(Boolean) as Product[];
        const failed = results
          .filter((r) => r.status === 'fulfilled' && !r.value.success)
          .map((r) => (r.status === 'fulfilled' ? r.value : null))
          .filter(Boolean) as Array<{ product: Product; error: string }>;
        const successCount = successful.length;
        const failureCount = failed.length;

        // Log failed associations for debugging
        if (failed.length > 0) {
          console.warn('Failed associations:', failed.map((f) => ({
            product: f.product.name,
            error: f.error,
          })));
        }

        // Show appropriate message based on results
        if (failureCount === 0) {
          // All associations succeeded
          toast.success(CUSTOMER_CREATE_WITH_ASSOCIATIONS_SUCCESS(selectedProducts.length));
        } else {
          // Partial or full failure - show warning and navigation button
          if (successCount > 0) {
            // Partial failure
            toast.warning(CUSTOMER_CREATE_ASSOCIATIONS_PARTIAL_FAILURE(successCount, failureCount), {
              autoClose: 6000,
            });
          } else {
            // All associations failed
            toast.warning(CUSTOMER_CREATE_ASSOCIATIONS_ALL_FAILURE, {
              autoClose: 6000,
            });
          }
          // Show navigation button immediately (extracted to avoid code duplication)
          toast.info(
            <div className="flex flex-col gap-2">
              <p>{MANAGE_ASSOCIATIONS_IN_DETAIL}</p>
              <Button
                variant="primary"
                size="sm"
                onClick={() => navigate(`/customers/${createdCustomer.id}/interactions`)}
                className="w-full"
              >
                前往客户互动历史
              </Button>
            </div>,
            {
              autoClose: 8000,
              closeOnClick: false,
            },
          );
        }
      } else {
        // No associations to create
        toast.success(CUSTOMER_CREATE_SUCCESS);
      }

      // Call the parent's onSubmit callback for consistency (it will handle navigation/state)
      // Note: Customer is already created, so parent's handleSubmit should not create it again
      await onSubmit(submitData);
    } catch (error: unknown) {
      const errorMessage = error instanceof Error ? error.message : '创建客户失败';
      setErrors({ submit: errorMessage });
      toast.error(errorMessage);
      // Re-throw to let parent handle it
      throw error;
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleChange = (field: keyof CreateCustomerDto, value: CreateCustomerDto[keyof CreateCustomerDto]) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    if (errors[field]) {
      setErrors((prev) => {
        const newErrors = { ...prev };
        delete newErrors[field];
        return newErrors;
      });
    }
  };

  const availableCustomerTypes = getAvailableCustomerTypes();

  return (
    <form onSubmit={handleSubmit} className="space-y-monday-6">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-monday-6">
        <Input
          id="name"
          label="客户名称"
          type="text"
          value={formData.name}
          onChange={(e) => handleChange('name', e.target.value)}
          error={!!errors.name}
          errorMessage={errors.name}
          maxLength={255}
          required
        />


        <div className="flex flex-col gap-monday-2">
          <label htmlFor="customerType" className="text-monday-sm font-semibold text-monday-text">
            客户类型 <span className="text-red-500">*</span>
          </label>
          <select
            id="customerType"
            value={formData.customerType}
            onChange={(e) => handleChange('customerType', e.target.value as 'BUYER' | 'SUPPLIER')}
            disabled={availableCustomerTypes.length === 1}
            className={`px-monday-3 py-monday-2 border rounded-monday-md focus:outline-none focus:ring-2 focus:ring-blue-500 ${
              errors.customerType ? 'border-red-500' : 'border-gray-300'
            } ${availableCustomerTypes.length === 1 ? 'bg-gray-100 cursor-not-allowed' : ''}`}
            required
          >
            {availableCustomerTypes.map((type) => (
              <option key={type} value={type}>
                {type === 'BUYER' ? '采购商' : '供应商'}
              </option>
            ))}
          </select>
          {errors.customerType && (
            <p className="text-monday-xs text-red-500">{errors.customerType}</p>
          )}
        </div>

        <Input
          id="domainName"
          label="域名"
          type="text"
          value={formData.domainName || ''}
          onChange={(e) => handleChange('domainName', e.target.value)}
          maxLength={255}
        />

        <Input
          id="address"
          label="地址"
          type="text"
          value={formData.address || ''}
          onChange={(e) => handleChange('address', e.target.value)}
          error={!!errors.address}
          errorMessage={errors.address}
          maxLength={1000}
        />

        <Input
          id="city"
          label="城市"
          type="text"
          value={formData.city || ''}
          onChange={(e) => handleChange('city', e.target.value)}
          maxLength={100}
        />

        <Input
          id="state"
          label="州/省"
          type="text"
          value={formData.state || ''}
          onChange={(e) => handleChange('state', e.target.value)}
          maxLength={100}
        />

        <Input
          id="country"
          label="国家"
          type="text"
          value={formData.country || ''}
          onChange={(e) => handleChange('country', e.target.value)}
          maxLength={100}
        />

        <Input
          id="postalCode"
          label="邮编"
          type="text"
          value={formData.postalCode || ''}
          onChange={(e) => handleChange('postalCode', e.target.value)}
          maxLength={20}
        />

        <Input
          id="industry"
          label="行业"
          type="text"
          value={formData.industry || ''}
          onChange={(e) => handleChange('industry', e.target.value)}
          error={!!errors.industry}
          errorMessage={errors.industry}
          maxLength={100}
        />

        <Input
          id="employees"
          label="员工数"
          type="number"
          value={formData.employees?.toString() || ''}
          onChange={(e) => handleChange('employees', e.target.value ? parseInt(e.target.value, 10) : undefined)}
          error={!!errors.employees}
          errorMessage={errors.employees}
          min={1}
          max={1000000}
        />

        <Input
          id="website"
          label="网站"
          type="url"
          value={formData.website || ''}
          onChange={(e) => handleChange('website', e.target.value)}
          maxLength={255}
        />

        <Input
          id="phone"
          label="电话"
          type="tel"
          value={formData.phone || ''}
          onChange={(e) => handleChange('phone', e.target.value)}
          maxLength={50}
        />

        <Input
          id="email"
          label="邮箱"
          type="email"
          value={formData.email || ''}
          onChange={(e) => handleChange('email', e.target.value)}
          error={!!errors.email}
          errorMessage={errors.email}
          maxLength={255}
          placeholder="example@company.com"
        />
      </div>

      <div>
        <label htmlFor="notes" className="text-monday-sm font-semibold text-monday-text block mb-monday-2">
          备注
        </label>
        <textarea
          id="notes"
          value={formData.notes || ''}
          onChange={(e) => handleChange('notes', e.target.value)}
          rows={4}
          maxLength={5000}
          className={`w-full px-monday-3 py-monday-2 border rounded-monday-md focus:outline-none focus:ring-2 focus:ring-blue-500 ${
            errors.notes ? 'border-red-500' : 'border-gray-300'
          }`}
        />
        {errors.notes && (
          <p className="text-monday-xs text-red-500 mt-monday-1">{errors.notes}</p>
        )}
      </div>

      {/* Association Section - Collapsible */}
      <div className="border border-gray-200 rounded-monday-md p-monday-4">
        <button
          type="button"
          onClick={() => setIsAssociationExpanded(!isAssociationExpanded)}
          className="w-full flex items-center justify-between text-monday-base font-semibold text-monday-text hover:text-primary-blue transition-colors"
          aria-expanded={isAssociationExpanded}
          aria-controls="association-section"
        >
          <span>关联产品（可选）</span>
          <span className="text-monday-text-secondary">
            {isAssociationExpanded ? '▼' : '▶'}
          </span>
        </button>

        {isAssociationExpanded && (
          <div
            id="association-section"
            className="mt-monday-4 transition-all duration-200"
          >
            <div className="flex flex-col gap-monday-2">
              <label className="text-monday-sm font-semibold text-monday-text">
                选择要关联的产品
              </label>
              <ProductMultiSelect
                selectedProducts={selectedProducts}
                onChange={setSelectedProducts}
                placeholder="搜索产品名称、HS编码或类别..."
                disabled={isSubmitting}
              />
              <span className="text-monday-xs text-monday-text-placeholder">
                创建客户后，系统将自动为选中的产品建立关联关系
              </span>
            </div>
          </div>
        )}
      </div>

      {errors.submit && (
        <div className="bg-red-50 border border-red-200 text-red-700 px-monday-4 py-monday-3 rounded-monday-md">
          {errors.submit}
        </div>
      )}

      <div className="flex justify-end gap-monday-4">
        <Button type="button" variant="outline" onClick={onCancel}>
          取消
        </Button>
        <Button type="submit" disabled={isSubmitting}>
          {isSubmitting ? '创建中...' : '创建客户'}
        </Button>
      </div>
    </form>
  );
};

